from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import TypeDecorator

from diffdx.db.base import Base
from diffdx.db.types import GUID

TestCategory = Enum("blood", "imaging", "other", name="test_category")
TestPriority = Enum("routine", "urgent", "stat", name="test_priority")
TestResultStatus = Enum("pending", "normal", "abnormal", "critical", name="test_result_status")
PlanItemSource = Enum("ai", "doctor", name="plan_item_source")
SecondOpinionStatus = Enum("pending", "responded", name="second_opinion_status")


class _JSONB(TypeDecorator):
    """JSONB on Postgres, plain JSON on SQLite — for genuinely schemaless AI output."""

    impl = JSON
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(JSONB())
        return dialect.type_descriptor(JSON())


class DiagnosticSession(Base):
    """A completed (or in-progress) AI diagnostic conversation.

    id matches the session_id generated by loop1/session.py — not DB-generated.
    """

    __tablename__ = "diagnostic_sessions"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True)
    patient_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID, ForeignKey("patients.user_id", ondelete="SET NULL"), index=True
    )

    chief_complaint: Mapped[str | None] = mapped_column(Text)
    primary_diagnosis: Mapped[str | None] = mapped_column(String(500))
    termination_reason: Mapped[str | None] = mapped_column(String(50))

    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    total_turns: Mapped[int | None] = mapped_column(Integer)

    # AI-generated, genuinely schemaless — explicitly allowed as JSONB by the spec.
    final_differential: Mapped[list | None] = mapped_column(_JSONB)
    closing_turn: Mapped[dict | None] = mapped_column(_JSONB)

    created_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), onupdate=func.now(), nullable=False
    )

    turns: Mapped[list["SessionTurn"]] = relationship(back_populates="session", cascade="all, delete-orphan")


class SessionTurn(Base):
    __tablename__ = "session_turns"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    session_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("diagnostic_sessions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    turn_index: Mapped[int] = mapped_column(Integer, nullable=False)

    question: Mapped[str | None] = mapped_column(Text)
    rationale: Mapped[str | None] = mapped_column(Text)
    biggest_uncertainty: Mapped[str | None] = mapped_column(Text)
    patient_answer: Mapped[str | None] = mapped_column(Text)
    confidence: Mapped[float | None] = mapped_column(Float)

    # Raw per-turn AI payload — schemaless by nature (see DoctorTurnOutput in loop1).
    differential: Mapped[list | None] = mapped_column(_JSONB)
    doctor_output: Mapped[dict | None] = mapped_column(_JSONB)

    created_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)

    session: Mapped[DiagnosticSession] = relationship(back_populates="turns")

    __table_args__ = (
        UniqueConstraint("session_id", "turn_index", name="uq_session_turns_session_id_turn_index"),
    )


class SuggestedTest(Base):
    """A test the AI/doctor ordered, plus its result once recorded.

    Merges TestOrderItem + TestResultItem from the legacy API — a result
    always attaches to an existing order by id in the current code.
    """

    __tablename__ = "suggested_tests"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False, index=True
    )
    test: Mapped[str] = mapped_column(String(300), nullable=False)
    category: Mapped[str] = mapped_column(TestCategory, nullable=False)
    priority: Mapped[str] = mapped_column(TestPriority, nullable=False, server_default="routine")
    notes: Mapped[str | None] = mapped_column(Text)
    ordered_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)

    result: Mapped[str | None] = mapped_column(Text)
    result_status: Mapped[str | None] = mapped_column(TestResultStatus)
    result_recorded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    appointment: Mapped["Appointment"] = relationship()


class Prescription(Base):
    __tablename__ = "prescriptions"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False, index=True
    )
    drug: Mapped[str] = mapped_column(String(300), nullable=False)
    dose: Mapped[str] = mapped_column(String(100), nullable=False)
    route: Mapped[str] = mapped_column(String(50), nullable=False, server_default="oral")
    frequency: Mapped[str] = mapped_column(String(100), nullable=False)
    duration: Mapped[str] = mapped_column(String(100), nullable=False)
    meal_timing: Mapped[str | None] = mapped_column(String(100))
    notes: Mapped[str | None] = mapped_column(Text)
    prescribed_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)

    appointment: Mapped["Appointment"] = relationship()


class Referral(Base):
    """1:1 with an appointment — a doctor referring the patient elsewhere."""

    __tablename__ = "referrals"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    specialty: Mapped[str] = mapped_column(String(100), nullable=False)
    to_doctor: Mapped[str | None] = mapped_column(String(200))  # blank = any available specialist
    urgency: Mapped[str] = mapped_column(String(50), nullable=False, server_default="Routine")
    notes: Mapped[str | None] = mapped_column(Text)
    internal_note: Mapped[str | None] = mapped_column(Text)  # doctor-only, never returned to patients
    referred_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)

    appointment: Mapped["Appointment"] = relationship()


class SecondOpinion(Base):
    """A doctor-to-doctor consult request tied to an appointment."""

    __tablename__ = "second_opinions"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False, index=True
    )
    from_doctor_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("doctors.user_id", ondelete="CASCADE"), nullable=False
    )
    to_doctor_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("doctors.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    patient_summary: Mapped[str | None] = mapped_column(Text)
    note: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(SecondOpinionStatus, nullable=False, server_default="pending")
    response: Mapped[str | None] = mapped_column(Text)
    requested_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)
    responded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    appointment: Mapped["Appointment"] = relationship()


class TreatmentPlanItem(Base):
    __tablename__ = "treatment_plan_items"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False, index=True
    )
    text: Mapped[str] = mapped_column(Text, nullable=False)
    approved: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    source: Mapped[str] = mapped_column(PlanItemSource, nullable=False, server_default="ai")
    created_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)

    appointment: Mapped["Appointment"] = relationship()
