from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    false,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from diffdx.db.base import Base
from diffdx.db.models.clinical import _JSONB
from diffdx.db.types import GUID

AppointmentStatus = Enum(
    "upcoming", "confirmed", "seen", "no_show", "cancelled", name="appointment_status"
)
UrgencyTier = Enum("emergency", "urgent", "routine", name="urgency_tier")
WaitlistStatus = Enum("waiting", "notified", "cancelled", name="waitlist_status")
RescheduleProposalStatus = Enum("pending", "accepted", "declined", name="reschedule_proposal_status")


class DoctorSlot(Base):
    """A single open slot a doctor has published for booking."""

    __tablename__ = "doctor_slots"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("doctors.user_id", ondelete="CASCADE"), nullable=False
    )
    slot_datetime: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    is_available: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")

    created_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), onupdate=func.now(), nullable=False
    )

    doctor: Mapped["Doctor"] = relationship(back_populates="slots")

    __table_args__ = (
        UniqueConstraint("doctor_id", "slot_datetime", name="uq_doctor_slots_doctor_id_slot_datetime"),
        Index("ix_doctor_slots_doctor_id", "doctor_id"),
    )


class BlockedDate(Base):
    """A date a doctor has marked as unavailable — no slots should appear."""

    __tablename__ = "blocked_dates"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("doctors.user_id", ondelete="CASCADE"), nullable=False
    )
    date: Mapped[str] = mapped_column(String(10), nullable=False)  # "YYYY-MM-DD"
    reason: Mapped[str | None] = mapped_column(String(500))

    created_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)

    doctor: Mapped["Doctor"] = relationship(back_populates="blocked_dates")

    __table_args__ = (
        UniqueConstraint("doctor_id", "date", name="uq_blocked_dates_doctor_id_date"),
    )


class Appointment(Base):
    __tablename__ = "appointments"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)

    # The AI diagnostic session that led to this booking, if any. Sessions are
    # generated by loop1/session.py, not FK'd — a session may exist only in
    # logs/final_records on disk and not yet have a DiagnosticSession row.
    session_id: Mapped[str | None] = mapped_column(String(36), index=True)

    patient_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("patients.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("doctors.user_id", ondelete="RESTRICT"), nullable=False, index=True
    )

    slot_datetime: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    status: Mapped[str] = mapped_column(AppointmentStatus, nullable=False, server_default="upcoming", index=True)
    urgency: Mapped[str] = mapped_column(UrgencyTier, nullable=False, server_default="routine")

    booked_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cancelled_by: Mapped[str | None] = mapped_column(String(50))

    note: Mapped[str | None] = mapped_column(Text)
    is_followup: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")

    # Self-referential FKs — a cancelled/rescheduled appointment chains to the
    # one that replaced it, or the one it followed up on. SET NULL so deleting
    # an old appointment doesn't cascade into deleting its successors.
    parent_appointment_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID, ForeignKey("appointments.id", ondelete="SET NULL")
    )
    rescheduled_from_id: Mapped[uuid.UUID | None] = mapped_column(
        GUID, ForeignKey("appointments.id", ondelete="SET NULL")
    )

    chief_complaint: Mapped[str | None] = mapped_column(Text)
    primary_diagnosis: Mapped[str | None] = mapped_column(String(500))

    # Doctor-confirmed diagnosis disclosure (DOCTOR_CONFIRMED_DIAGNOSIS_PLAN.md).
    # Deliberately a separate column from primary_diagnosis (the AI's own
    # output, set at booking time) — this is only ever written by a doctor
    # explicitly submitting/reviewing text via PATCH .../diagnosis, never
    # auto-derived from primary_diagnosis. The patient-facing report only
    # ever reads this field, never primary_diagnosis.
    confirmed_diagnosis: Mapped[str | None] = mapped_column(String(500))
    diagnosis_confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Snapshot of patient vitals at booking time (demographics can change later).
    patient_age: Mapped[int | None]
    patient_sex: Mapped[str | None] = mapped_column(String(20))
    patient_bmi: Mapped[float | None] = mapped_column(Float)

    rating_stars: Mapped[int | None] = mapped_column(Integer)
    rating_comment: Mapped[str | None] = mapped_column(Text)
    rating_submitted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Remaining blob-only fields cut over in Task 20 — plain scalar columns
    # since each is already 1:1 with the appointment dict (whole-value
    # overwrite, no sub-entity shape of its own).
    doctor_summary: Mapped[str | None] = mapped_column(Text)
    summary_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    doctor_notes: Mapped[str | None] = mapped_column(Text)
    notes_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    patient_tags: Mapped[list | None] = mapped_column(_JSONB)
    tags_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Plain "false" as a server_default string literal reads back truthy on
    # SQLite (it inserts the text "false", which Boolean then coerces as
    # non-empty -> True) — found live while testing this column.
    # false()/true() render an actual dialect-correct boolean literal instead.
    reminder_sent: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=false())

    created_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), onupdate=func.now(), nullable=False
    )

    patient: Mapped["Patient"] = relationship(foreign_keys=[patient_id])
    doctor: Mapped["Doctor"] = relationship(foreign_keys=[doctor_id])

    __table_args__ = (
        # The core guarantee this whole task exists to prove: the DB itself
        # makes double-booking impossible. Partial index excludes cancelled
        # rows so a cancelled+rebooked slot doesn't collide with itself.
        Index(
            "uq_appointments_doctor_slot_active",
            "doctor_id",
            "slot_datetime",
            unique=True,
            postgresql_where=(status != "cancelled"),
            sqlite_where=(status != "cancelled"),
        ),
        Index("ix_appointments_slot_datetime", "slot_datetime"),
    )


class RescheduleProposal(Base):
    """1:1 with an appointment — a doctor-proposed new slot awaiting the
    patient's accept/decline. Blob always assigns a single dict, overwritten
    on every propose, so this is upsert-shaped like Referral, not a list."""

    __tablename__ = "reschedule_proposals"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    appointment_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("appointments.id", ondelete="CASCADE"), nullable=False, unique=True
    )
    proposed_slot: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    reason: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(RescheduleProposalStatus, nullable=False, server_default="pending")
    proposed_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)
    proposed_by: Mapped[str | None] = mapped_column(String(200))
    responded_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    appointment: Mapped["Appointment"] = relationship()


class Waitlist(Base):
    __tablename__ = "waitlist"

    id: Mapped[uuid.UUID] = mapped_column(GUID, primary_key=True, default=uuid.uuid4)
    patient_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("patients.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    doctor_id: Mapped[uuid.UUID] = mapped_column(
        GUID, ForeignKey("doctors.user_id", ondelete="CASCADE"), nullable=False, index=True
    )
    note: Mapped[str | None] = mapped_column(String(1000))
    status: Mapped[str] = mapped_column(WaitlistStatus, nullable=False, server_default="waiting")
    joined_at: Mapped[datetime] = mapped_column(server_default=func.now(), nullable=False)

    __table_args__ = (
        Index("ix_waitlist_doctor_id_status", "doctor_id", "status"),
    )
