"""add sarvam usage events table

Revision ID: 7834f7f6fed4
Revises: a3f8c1d92e77
Create Date: 2026-09-15 06:16:45.618120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import diffdx.db.types


# revision identifiers, used by Alembic.
revision: str = '7834f7f6fed4'
down_revision: Union[str, None] = 'a3f8c1d92e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sarvam_usage_events',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('call_site', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sarvam_usage_events'))
    )
    op.create_index(op.f('ix_sarvam_usage_events_recorded_at'), 'sarvam_usage_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sarvam_usage_events_session_id'), 'sarvam_usage_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_sarvam_usage_events_source'), 'sarvam_usage_events', ['source'], unique=False)
    # NOTE: autogenerate also proposed `op.drop_table('store')` here — REMOVED.
    # `store` is diffdx.legacy_store's blob-store table, created via raw SQL
    # rather than a SQLAlchemy model, so it has no entry in Base.metadata and
    # autogenerate sees it as "extra" and proposes dropping it. Doing so
    # would destroy most of the application's live data — see the same note
    # in 915ef5eaf914_add_llm_usage_events_table.py. Left in place, untouched.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed recreating `store` here (with a
    # subtly wrong schema, `collection` nullable instead of the real table's
    # PRIMARY KEY) — REMOVED for the same reason as upgrade(): this
    # migration never touches `store`, so downgrade must not either.
    op.drop_index(op.f('ix_sarvam_usage_events_source'), table_name='sarvam_usage_events')
    op.drop_index(op.f('ix_sarvam_usage_events_session_id'), table_name='sarvam_usage_events')
    op.drop_index(op.f('ix_sarvam_usage_events_recorded_at'), table_name='sarvam_usage_events')
    op.drop_table('sarvam_usage_events')
    # ### end Alembic commands ###
