"""add llm_usage_events table

Revision ID: 915ef5eaf914
Revises: dc1320aa68aa
Create Date: 2026-09-09 07:22:01.042406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import diffdx.db.types


# revision identifiers, used by Alembic.
revision: str = '915ef5eaf914'
down_revision: Union[str, None] = 'dc1320aa68aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_events',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('call_site', sa.String(length=50), nullable=False),
    sa.Column('model_configured', sa.String(length=200), nullable=True),
    sa.Column('model_actual', sa.String(length=200), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens_estimated', sa.Integer(), nullable=True),
    sa.Column('completion_tokens_is_estimate', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage_events'))
    )
    op.create_index(op.f('ix_llm_usage_events_recorded_at'), 'llm_usage_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_llm_usage_events_session_id'), 'llm_usage_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_events_source'), 'llm_usage_events', ['source'], unique=False)
    # NOTE: autogenerate also proposed `op.drop_table('store')` here — REMOVED.
    # `store` is diffdx.legacy_store's blob-store table (users, appointments,
    # messages, session reports, uploaded files, ...), created via raw SQL
    # (CREATE TABLE IF NOT EXISTS) rather than a SQLAlchemy model, so it has
    # no entry in Base.metadata and autogenerate sees it as "extra" and
    # proposes dropping it. Doing so would destroy most of the application's
    # live data. Left in place, untouched, deliberately.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed recreating `store` here (with a
    # subtly wrong schema, `collection` nullable instead of the real
    # table's PRIMARY KEY) — REMOVED for the same reason as upgrade():
    # this migration never touches `store`, so downgrade must not either.
    op.drop_index(op.f('ix_llm_usage_events_source'), table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_session_id'), table_name='llm_usage_events')
    op.drop_index(op.f('ix_llm_usage_events_recorded_at'), table_name='llm_usage_events')
    op.drop_table('llm_usage_events')
    # ### end Alembic commands ###
