"""add remaining blob-only appointment fields

Revision ID: 9ef2c0edf03e
Revises: c9231e860c45
Create Date: 2026-09-04 23:41:52.033348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import diffdx.db.types
import diffdx.db.models.clinical


# revision identifiers, used by Alembic.
revision: str = '9ef2c0edf03e'
down_revision: Union[str, None] = 'c9231e860c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_intakes',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('feeling', sa.Text(), nullable=True),
    sa.Column('symptoms', diffdx.db.models.clinical._JSONB(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('medications', diffdx.db.models.clinical._JSONB(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('tests_done', diffdx.db.models.clinical._JSONB(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_intakes_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_intakes')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_appointment_intakes_appointment_id'))
    )
    op.create_table('prescription_history_batches',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prescriptions', diffdx.db.models.clinical._JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_prescription_history_batches_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription_history_batches'))
    )
    op.create_index(op.f('ix_prescription_history_batches_appointment_id'), 'prescription_history_batches', ['appointment_id'], unique=False)
    op.create_table('refill_requests',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('medications', diffdx.db.models.clinical._JSONB(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'fulfilled', name='refill_request_status'), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_refill_requests_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refill_requests')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_refill_requests_appointment_id'))
    )
    op.create_table('reschedule_proposals',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('proposed_slot', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='reschedule_proposal_status'), server_default='pending', nullable=False),
    sa.Column('proposed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('proposed_by', sa.String(length=200), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_reschedule_proposals_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reschedule_proposals')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_reschedule_proposals_appointment_id'))
    )
    # NOTE: autogenerate also proposed `op.drop_table('store')` — the legacy
    # blob-store table isn't a mapped model (it's hand-managed via raw SQL in
    # web/api.py._db_load/_db_save) so Alembic sees it as "unknown, remove
    # it." It's still authoritative for every route not yet dual-written;
    # dropping it here would be catastrophic data loss. Deliberately omitted.
    op.add_column('appointments', sa.Column('doctor_summary', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('doctor_notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('notes_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('patient_tags', diffdx.db.models.clinical._JSONB(), nullable=True))
    op.add_column('appointments', sa.Column('tags_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('reminder_sent', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reminder_sent')
    op.drop_column('appointments', 'tags_updated_at')
    op.drop_column('appointments', 'patient_tags')
    op.drop_column('appointments', 'notes_updated_at')
    op.drop_column('appointments', 'doctor_notes')
    op.drop_column('appointments', 'summary_updated_at')
    op.drop_column('appointments', 'doctor_summary')
    op.drop_table('reschedule_proposals')
    op.drop_table('refill_requests')
    op.drop_index(op.f('ix_prescription_history_batches_appointment_id'), table_name='prescription_history_batches')
    op.drop_table('prescription_history_batches')
    op.drop_table('appointment_intakes')
    # ### end Alembic commands ###
