"""add dsr erasure requests table

Revision ID: c46f6274d2ea
Revises: 915ef5eaf914
Create Date: 2026-09-11 19:41:36.008550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import diffdx.db.types


# revision identifiers, used by Alembic.
revision: str = 'c46f6274d2ea'
down_revision: Union[str, None] = '915ef5eaf914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerate also proposed `op.drop_table('store')` here — that's
    # the same raw-SQL-managed (not ORM-managed) legacy blob-store table this
    # repo already hit in 915ef5eaf914_add_llm_usage_events_table.py. Removed
    # deliberately; 'store' is not something any migration should touch.
    op.create_table('dsr_erasure_requests',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('user_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', diffdx.db.types.GUID(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_dsr_erasure_requests_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dsr_erasure_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dsr_erasure_requests'))
    )
    op.create_index(op.f('ix_dsr_erasure_requests_user_id'), 'dsr_erasure_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsr_erasure_requests_user_id'), table_name='dsr_erasure_requests')
    op.drop_table('dsr_erasure_requests')
    # ### end Alembic commands ###
