"""initial schema

Revision ID: c9231e860c45
Revises: 
Create Date: 2026-09-03 01:04:32.405416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import diffdx.db.types


# revision identifiers, used by Alembic.
revision: str = 'c9231e860c45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='user_role'), server_default='patient', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # Case-insensitive email uniqueness — autogenerate can't detect/compare
    # expression indexes, so this is created by hand and must be kept in
    # sync manually if the users table ever changes.
    op.execute(
        "CREATE UNIQUE INDEX uq_users_email_lower ON users (lower(email))"
    )
    op.create_table('audit_log_entries',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('actor_user_id', diffdx.db.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_entries_actor_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log_entries'))
    )
    op.create_index(op.f('ix_audit_log_entries_action'), 'audit_log_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_actor_user_id'), 'audit_log_entries', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_created_at'), 'audit_log_entries', ['created_at'], unique=False)
    op.create_table('doctors',
    sa.Column('user_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('doctor_id', sa.String(length=50), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('hospital', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('avatar_initials', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_doctors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_doctors')),
    sa.UniqueConstraint('doctor_id', name=op.f('uq_doctors_doctor_id'))
    )
    op.create_index(op.f('ix_doctors_specialty'), 'doctors', ['specialty'], unique=False)
    op.create_table('patients',
    sa.Column('user_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('allergies', sa.String(length=2000), nullable=True),
    sa.Column('chronic_conditions', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_patients'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('user_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('doctor_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('slot_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'confirmed', 'seen', 'no_show', 'cancelled', name='appointment_status'), server_default='upcoming', nullable=False),
    sa.Column('urgency', sa.Enum('emergency', 'urgent', 'routine', name='urgency_tier'), server_default='routine', nullable=False),
    sa.Column('booked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_followup', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('parent_appointment_id', diffdx.db.types.GUID(), nullable=True),
    sa.Column('rescheduled_from_id', diffdx.db.types.GUID(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=500), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_sex', sa.String(length=20), nullable=True),
    sa.Column('patient_bmi', sa.Float(), nullable=True),
    sa.Column('rating_stars', sa.Integer(), nullable=True),
    sa.Column('rating_comment', sa.Text(), nullable=True),
    sa.Column('rating_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], name=op.f('fk_appointments_doctor_id_doctors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_appointment_id'], ['appointments.id'], name=op.f('fk_appointments_parent_appointment_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], name=op.f('fk_appointments_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], name=op.f('fk_appointments_rescheduled_from_id_appointments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_session_id'), 'appointments', ['session_id'], unique=False)
    op.create_index('ix_appointments_slot_datetime', 'appointments', ['slot_datetime'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('uq_appointments_doctor_slot_active', 'appointments', ['doctor_id', 'slot_datetime'], unique=True, postgresql_where=sa.text("status != 'cancelled'"), sqlite_where=sa.text("status != 'cancelled'"))
    op.create_table('blocked_dates',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('doctor_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], name=op.f('fk_blocked_dates_doctor_id_doctors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocked_dates')),
    sa.UniqueConstraint('doctor_id', 'date', name='uq_blocked_dates_doctor_id_date')
    )
    op.create_table('dependents',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('patient_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=30), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('allergies', sa.String(length=2000), nullable=True),
    sa.Column('chronic_conditions', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], name=op.f('fk_dependents_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependents'))
    )
    op.create_index(op.f('ix_dependents_patient_id'), 'dependents', ['patient_id'], unique=False)
    op.create_table('diagnostic_sessions',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('patient_id', diffdx.db.types.GUID(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=500), nullable=True),
    sa.Column('termination_reason', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.Column('final_differential', diffdx.db.models.clinical._JSONB(), nullable=True),
    sa.Column('closing_turn', diffdx.db.models.clinical._JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], name=op.f('fk_diagnostic_sessions_patient_id_patients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnostic_sessions'))
    )
    op.create_index(op.f('ix_diagnostic_sessions_patient_id'), 'diagnostic_sessions', ['patient_id'], unique=False)
    op.create_table('doctor_slots',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('doctor_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('slot_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], name=op.f('fk_doctor_slots_doctor_id_doctors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_slots')),
    sa.UniqueConstraint('doctor_id', 'slot_datetime', name='uq_doctor_slots_doctor_id_slot_datetime')
    )
    op.create_index('ix_doctor_slots_doctor_id', 'doctor_slots', ['doctor_id'], unique=False)
    op.create_table('message_threads',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('patient_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('doctor_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], name=op.f('fk_message_threads_doctor_id_doctors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], name=op.f('fk_message_threads_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_threads')),
    sa.UniqueConstraint('patient_id', 'doctor_id', name='uq_message_threads_patient_id_doctor_id')
    )
    op.create_index(op.f('ix_message_threads_doctor_id'), 'message_threads', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_message_threads_patient_id'), 'message_threads', ['patient_id'], unique=False)
    op.create_table('waitlist',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('patient_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('doctor_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'notified', 'cancelled', name='waitlist_status'), server_default='waiting', nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.user_id'], name=op.f('fk_waitlist_doctor_id_doctors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], name=op.f('fk_waitlist_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waitlist'))
    )
    op.create_index(op.f('ix_waitlist_doctor_id'), 'waitlist', ['doctor_id'], unique=False)
    op.create_index('ix_waitlist_doctor_id_status', 'waitlist', ['doctor_id', 'status'], unique=False)
    op.create_index(op.f('ix_waitlist_patient_id'), 'waitlist', ['patient_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('thread_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=True),
    sa.Column('sender_role', sa.Enum('patient', 'doctor', name='message_sender_role'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('read', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_messages_appointment_id_appointments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], name=op.f('fk_messages_thread_id_message_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('drug', sa.String(length=300), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=50), server_default='oral', nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('meal_timing', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prescribed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_prescriptions_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    op.create_index(op.f('ix_prescriptions_appointment_id'), 'prescriptions', ['appointment_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('to_doctor', sa.String(length=200), nullable=True),
    sa.Column('urgency', sa.String(length=50), server_default='Routine', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('referred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_referrals_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_referrals_appointment_id'))
    )
    op.create_table('second_opinions',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('from_doctor_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('to_doctor_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('patient_summary', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'responded', name='second_opinion_status'), server_default='pending', nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_second_opinions_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_doctor_id'], ['doctors.user_id'], name=op.f('fk_second_opinions_from_doctor_id_doctors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_doctor_id'], ['doctors.user_id'], name=op.f('fk_second_opinions_to_doctor_id_doctors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_second_opinions'))
    )
    op.create_index(op.f('ix_second_opinions_appointment_id'), 'second_opinions', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_second_opinions_to_doctor_id'), 'second_opinions', ['to_doctor_id'], unique=False)
    op.create_table('session_turns',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('session_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('biggest_uncertainty', sa.Text(), nullable=True),
    sa.Column('patient_answer', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('differential', diffdx.db.models.clinical._JSONB(), nullable=True),
    sa.Column('doctor_output', diffdx.db.models.clinical._JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], name=op.f('fk_session_turns_session_id_diagnostic_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_turns')),
    sa.UniqueConstraint('session_id', 'turn_index', name='uq_session_turns_session_id_turn_index')
    )
    op.create_index(op.f('ix_session_turns_session_id'), 'session_turns', ['session_id'], unique=False)
    op.create_table('suggested_tests',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('test', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('blood', 'imaging', 'other', name='test_category'), nullable=False),
    sa.Column('priority', sa.Enum('routine', 'urgent', 'stat', name='test_priority'), server_default='routine', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('result_status', sa.Enum('pending', 'normal', 'abnormal', 'critical', name='test_result_status'), nullable=True),
    sa.Column('result_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_suggested_tests_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suggested_tests'))
    )
    op.create_index(op.f('ix_suggested_tests_appointment_id'), 'suggested_tests', ['appointment_id'], unique=False)
    op.create_table('treatment_plan_items',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source', sa.Enum('ai', 'doctor', name='plan_item_source'), server_default='ai', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_treatment_plan_items_appointment_id_appointments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_plan_items'))
    )
    op.create_index(op.f('ix_treatment_plan_items_appointment_id'), 'treatment_plan_items', ['appointment_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', diffdx.db.types.GUID(), nullable=False),
    sa.Column('appointment_id', diffdx.db.types.GUID(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('suggested_test_id', diffdx.db.types.GUID(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_uploaded_files_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggested_test_id'], ['suggested_tests.id'], name=op.f('fk_uploaded_files_suggested_test_id_suggested_tests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files'))
    )
    op.create_index(op.f('ix_uploaded_files_appointment_id'), 'uploaded_files', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_session_id'), 'uploaded_files', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_session_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_appointment_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_treatment_plan_items_appointment_id'), table_name='treatment_plan_items')
    op.drop_table('treatment_plan_items')
    op.drop_index(op.f('ix_suggested_tests_appointment_id'), table_name='suggested_tests')
    op.drop_table('suggested_tests')
    op.drop_index(op.f('ix_session_turns_session_id'), table_name='session_turns')
    op.drop_table('session_turns')
    op.drop_index(op.f('ix_second_opinions_to_doctor_id'), table_name='second_opinions')
    op.drop_index(op.f('ix_second_opinions_appointment_id'), table_name='second_opinions')
    op.drop_table('second_opinions')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_prescriptions_appointment_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_waitlist_patient_id'), table_name='waitlist')
    op.drop_index('ix_waitlist_doctor_id_status', table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_doctor_id'), table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index(op.f('ix_message_threads_patient_id'), table_name='message_threads')
    op.drop_index(op.f('ix_message_threads_doctor_id'), table_name='message_threads')
    op.drop_table('message_threads')
    op.drop_index('ix_doctor_slots_doctor_id', table_name='doctor_slots')
    op.drop_table('doctor_slots')
    op.drop_index(op.f('ix_diagnostic_sessions_patient_id'), table_name='diagnostic_sessions')
    op.drop_table('diagnostic_sessions')
    op.drop_index(op.f('ix_dependents_patient_id'), table_name='dependents')
    op.drop_table('dependents')
    op.drop_table('blocked_dates')
    op.drop_index('uq_appointments_doctor_slot_active', table_name='appointments', postgresql_where=sa.text("status != 'cancelled'"), sqlite_where=sa.text("status != 'cancelled'"))
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index('ix_appointments_slot_datetime', table_name='appointments')
    op.drop_index(op.f('ix_appointments_session_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_specialty'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_audit_log_entries_created_at'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_actor_user_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_action'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.execute("DROP INDEX uq_users_email_lower")
    op.drop_table('users')
    # ### end Alembic commands ###
